package com.smlearning.domain.entity;

public class CourseSchedule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_schedule.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_schedule.week_name
     *
     * @mbggenerated
     */
    private String weekName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_schedule.level_one
     *
     * @mbggenerated
     */
    private String levelOne;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_schedule.level_two
     *
     * @mbggenerated
     */
    private String levelTwo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_schedule.level_three
     *
     * @mbggenerated
     */
    private String levelThree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_schedule.level_four
     *
     * @mbggenerated
     */
    private String levelFour;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_schedule.level_five
     *
     * @mbggenerated
     */
    private String levelFive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_schedule.level_six
     *
     * @mbggenerated
     */
    private String levelSix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_schedule.level_seven
     *
     * @mbggenerated
     */
    private String levelSeven;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_schedule.level_eight
     *
     * @mbggenerated
     */
    private String levelEight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_schedule.super_grade
     *
     * @mbggenerated
     */
    private String superGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_schedule.super_class
     *
     * @mbggenerated
     */
    private String superClass;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_schedule.id
     *
     * @return the value of course_schedule.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_schedule.id
     *
     * @param id the value for course_schedule.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_schedule.week_name
     *
     * @return the value of course_schedule.week_name
     *
     * @mbggenerated
     */
    public String getWeekName() {
        return weekName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_schedule.week_name
     *
     * @param weekName the value for course_schedule.week_name
     *
     * @mbggenerated
     */
    public void setWeekName(String weekName) {
        this.weekName = weekName == null ? null : weekName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_schedule.level_one
     *
     * @return the value of course_schedule.level_one
     *
     * @mbggenerated
     */
    public String getLevelOne() {
        return levelOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_schedule.level_one
     *
     * @param levelOne the value for course_schedule.level_one
     *
     * @mbggenerated
     */
    public void setLevelOne(String levelOne) {
        this.levelOne = levelOne == null ? null : levelOne.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_schedule.level_two
     *
     * @return the value of course_schedule.level_two
     *
     * @mbggenerated
     */
    public String getLevelTwo() {
        return levelTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_schedule.level_two
     *
     * @param levelTwo the value for course_schedule.level_two
     *
     * @mbggenerated
     */
    public void setLevelTwo(String levelTwo) {
        this.levelTwo = levelTwo == null ? null : levelTwo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_schedule.level_three
     *
     * @return the value of course_schedule.level_three
     *
     * @mbggenerated
     */
    public String getLevelThree() {
        return levelThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_schedule.level_three
     *
     * @param levelThree the value for course_schedule.level_three
     *
     * @mbggenerated
     */
    public void setLevelThree(String levelThree) {
        this.levelThree = levelThree == null ? null : levelThree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_schedule.level_four
     *
     * @return the value of course_schedule.level_four
     *
     * @mbggenerated
     */
    public String getLevelFour() {
        return levelFour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_schedule.level_four
     *
     * @param levelFour the value for course_schedule.level_four
     *
     * @mbggenerated
     */
    public void setLevelFour(String levelFour) {
        this.levelFour = levelFour == null ? null : levelFour.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_schedule.level_five
     *
     * @return the value of course_schedule.level_five
     *
     * @mbggenerated
     */
    public String getLevelFive() {
        return levelFive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_schedule.level_five
     *
     * @param levelFive the value for course_schedule.level_five
     *
     * @mbggenerated
     */
    public void setLevelFive(String levelFive) {
        this.levelFive = levelFive == null ? null : levelFive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_schedule.level_six
     *
     * @return the value of course_schedule.level_six
     *
     * @mbggenerated
     */
    public String getLevelSix() {
        return levelSix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_schedule.level_six
     *
     * @param levelSix the value for course_schedule.level_six
     *
     * @mbggenerated
     */
    public void setLevelSix(String levelSix) {
        this.levelSix = levelSix == null ? null : levelSix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_schedule.level_seven
     *
     * @return the value of course_schedule.level_seven
     *
     * @mbggenerated
     */
    public String getLevelSeven() {
        return levelSeven;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_schedule.level_seven
     *
     * @param levelSeven the value for course_schedule.level_seven
     *
     * @mbggenerated
     */
    public void setLevelSeven(String levelSeven) {
        this.levelSeven = levelSeven == null ? null : levelSeven.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_schedule.level_eight
     *
     * @return the value of course_schedule.level_eight
     *
     * @mbggenerated
     */
    public String getLevelEight() {
        return levelEight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_schedule.level_eight
     *
     * @param levelEight the value for course_schedule.level_eight
     *
     * @mbggenerated
     */
    public void setLevelEight(String levelEight) {
        this.levelEight = levelEight == null ? null : levelEight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_schedule.super_grade
     *
     * @return the value of course_schedule.super_grade
     *
     * @mbggenerated
     */
    public String getSuperGrade() {
        return superGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_schedule.super_grade
     *
     * @param superGrade the value for course_schedule.super_grade
     *
     * @mbggenerated
     */
    public void setSuperGrade(String superGrade) {
        this.superGrade = superGrade == null ? null : superGrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_schedule.super_class
     *
     * @return the value of course_schedule.super_class
     *
     * @mbggenerated
     */
    public String getSuperClass() {
        return superClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_schedule.super_class
     *
     * @param superClass the value for course_schedule.super_class
     *
     * @mbggenerated
     */
    public void setSuperClass(String superClass) {
        this.superClass = superClass == null ? null : superClass.trim();
    }
}