package com.smlearning.domain.entity;

import java.util.Date;

import com.smlearning.domain.entity.enums.CourseStatusEnum;

public class Course {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_category_id
     *
     * @mbggenerated
     */
    private Long coursewareCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.lectuer
     *
     * @mbggenerated
     */
    private String lectuer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.hour
     *
     * @mbggenerated
     */
    private Integer hour;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.can_upload
     *
     * @mbggenerated
     */
    private String url;
    

   public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getTeacherDescription() {
		return teacherDescription;
	}

	public void setTeacherDescription(String teacherDescription) {
		this.teacherDescription = teacherDescription;
	}

private String description;

   /**
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column course.teacher_description
    *
    * @mbggenerated
    */
   private String teacherDescription;
    
    public String getPic() {
		return pic;
	}

	public void setPic(String pic) {
		this.pic = pic;
	}

	private String pic;
    
    
    public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.created_time
     *
     * @mbggenerated
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.creator
     *
     * @mbggenerated
     */
    private Long creator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.id
     *
     * @return the value of course.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.id
     *
     * @param id the value for course.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.name
     *
     * @return the value of course.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.name
     *
     * @param name the value for course.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_category_id
     *
     * @return the value of course.course_category_id
     *
     * @mbggenerated
     */
    public Long getCoursewareCategoryId() {
        return coursewareCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_category_id
     *
     * @param courseCategoryId the value for course.course_category_id
     *
     * @mbggenerated
     */
    public void setCoursewareCategoryId(Long coursewareCategoryId) {
        this.coursewareCategoryId = coursewareCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.lectuer
     *
     * @return the value of course.lectuer
     *
     * @mbggenerated
     */
    public String getLectuer() {
        return lectuer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.lectuer
     *
     * @param lectuer the value for course.lectuer
     *
     * @mbggenerated
     */
    public void setLectuer(String lectuer) {
        this.lectuer = lectuer == null ? null : lectuer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.hour
     *
     * @return the value of course.hour
     *
     * @mbggenerated
     */
    public Integer getHour() {
        return hour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.hour
     *
     * @param hour the value for course.hour
     *
     * @mbggenerated
     */
    public void setHour(Integer hour) {
        this.hour = hour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.status
     *
     * @return the value of course.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.status
     *
     * @param status the value for course.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.can_upload
     *
     * @return the value of course.can_upload
     *
     * @mbggenerated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.can_upload
     *
     * @param canUpload the value for course.can_upload
     *
     * @mbggenerated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.created_time
     *
     * @return the value of course.created_time
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.created_time
     *
     * @param createdTime the value for course.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.creator
     *
     * @return the value of course.creator
     *
     * @mbggenerated
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.creator
     *
     * @param creator the value for course.creator
     *
     * @mbggenerated
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }
    
    @SuppressWarnings("unused")
    private String statusName;

 	public String getStatusName() {
 		return CourseStatusEnum.valueOf(this.status).toString();
 	}
 	
 	private Long gradeId = 0L;
 	private Integer isPublic = 0;


  public Long getGradeId() {
    return gradeId;
  }

  public void setGradeId(Long gradeId) {
    this.gradeId = gradeId;
  }

  public Integer getIsPublic() {
    return isPublic;
  }

  public void setIsPublic(Integer isPublic) {
    this.isPublic = isPublic;
  }

  public void setStatusName(String statusName) {
    this.statusName = statusName;
  }
 	
}