package com.smlearning.domain.entity;

import java.util.Date;

public class CourseCourseware {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_courseware.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_courseware.course_id
     *
     * @mbggenerated
     */
    private Long courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_courseware.courseware_id
     *
     * @mbggenerated
     */
    private Long coursewareId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_courseware.creator
     *
     * @mbggenerated
     */
    private Long creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_courseware.created_time
     *
     * @mbggenerated
     */
    private Date createdTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_courseware.id
     *
     * @return the value of course_courseware.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_courseware.id
     *
     * @param id the value for course_courseware.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_courseware.course_id
     *
     * @return the value of course_courseware.course_id
     *
     * @mbggenerated
     */
    public Long getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_courseware.course_id
     *
     * @param courseId the value for course_courseware.course_id
     *
     * @mbggenerated
     */
    public void setCourseId(Long courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_courseware.courseware_id
     *
     * @return the value of course_courseware.courseware_id
     *
     * @mbggenerated
     */
    public Long getCoursewareId() {
        return coursewareId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_courseware.courseware_id
     *
     * @param coursewareId the value for course_courseware.courseware_id
     *
     * @mbggenerated
     */
    public void setCoursewareId(Long coursewareId) {
        this.coursewareId = coursewareId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_courseware.creator
     *
     * @return the value of course_courseware.creator
     *
     * @mbggenerated
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_courseware.creator
     *
     * @param creator the value for course_courseware.creator
     *
     * @mbggenerated
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_courseware.created_time
     *
     * @return the value of course_courseware.created_time
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_courseware.created_time
     *
     * @param createdTime the value for course_courseware.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }
}