package com.smlearning.domain.entity;

import java.util.ArrayList;
import java.util.List;

public class CourseScheduleExample extends BaseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table course_schedule
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table course_schedule
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table course_schedule
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_schedule
     *
     * @mbggenerated
     */
    public CourseScheduleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_schedule
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_schedule
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_schedule
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_schedule
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_schedule
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_schedule
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_schedule
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_schedule
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_schedule
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_schedule
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table course_schedule
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andWeekNameIsNull() {
            addCriterion("week_name is null");
            return (Criteria) this;
        }

        public Criteria andWeekNameIsNotNull() {
            addCriterion("week_name is not null");
            return (Criteria) this;
        }

        public Criteria andWeekNameEqualTo(String value) {
            addCriterion("week_name =", value, "weekName");
            return (Criteria) this;
        }

        public Criteria andWeekNameNotEqualTo(String value) {
            addCriterion("week_name <>", value, "weekName");
            return (Criteria) this;
        }

        public Criteria andWeekNameGreaterThan(String value) {
            addCriterion("week_name >", value, "weekName");
            return (Criteria) this;
        }

        public Criteria andWeekNameGreaterThanOrEqualTo(String value) {
            addCriterion("week_name >=", value, "weekName");
            return (Criteria) this;
        }

        public Criteria andWeekNameLessThan(String value) {
            addCriterion("week_name <", value, "weekName");
            return (Criteria) this;
        }

        public Criteria andWeekNameLessThanOrEqualTo(String value) {
            addCriterion("week_name <=", value, "weekName");
            return (Criteria) this;
        }

        public Criteria andWeekNameLike(String value) {
            addCriterion("week_name like", value, "weekName");
            return (Criteria) this;
        }

        public Criteria andWeekNameNotLike(String value) {
            addCriterion("week_name not like", value, "weekName");
            return (Criteria) this;
        }

        public Criteria andWeekNameIn(List<String> values) {
            addCriterion("week_name in", values, "weekName");
            return (Criteria) this;
        }

        public Criteria andWeekNameNotIn(List<String> values) {
            addCriterion("week_name not in", values, "weekName");
            return (Criteria) this;
        }

        public Criteria andWeekNameBetween(String value1, String value2) {
            addCriterion("week_name between", value1, value2, "weekName");
            return (Criteria) this;
        }

        public Criteria andWeekNameNotBetween(String value1, String value2) {
            addCriterion("week_name not between", value1, value2, "weekName");
            return (Criteria) this;
        }

        public Criteria andLevelOneIsNull() {
            addCriterion("level_one is null");
            return (Criteria) this;
        }

        public Criteria andLevelOneIsNotNull() {
            addCriterion("level_one is not null");
            return (Criteria) this;
        }

        public Criteria andLevelOneEqualTo(String value) {
            addCriterion("level_one =", value, "levelOne");
            return (Criteria) this;
        }

        public Criteria andLevelOneNotEqualTo(String value) {
            addCriterion("level_one <>", value, "levelOne");
            return (Criteria) this;
        }

        public Criteria andLevelOneGreaterThan(String value) {
            addCriterion("level_one >", value, "levelOne");
            return (Criteria) this;
        }

        public Criteria andLevelOneGreaterThanOrEqualTo(String value) {
            addCriterion("level_one >=", value, "levelOne");
            return (Criteria) this;
        }

        public Criteria andLevelOneLessThan(String value) {
            addCriterion("level_one <", value, "levelOne");
            return (Criteria) this;
        }

        public Criteria andLevelOneLessThanOrEqualTo(String value) {
            addCriterion("level_one <=", value, "levelOne");
            return (Criteria) this;
        }

        public Criteria andLevelOneLike(String value) {
            addCriterion("level_one like", value, "levelOne");
            return (Criteria) this;
        }

        public Criteria andLevelOneNotLike(String value) {
            addCriterion("level_one not like", value, "levelOne");
            return (Criteria) this;
        }

        public Criteria andLevelOneIn(List<String> values) {
            addCriterion("level_one in", values, "levelOne");
            return (Criteria) this;
        }

        public Criteria andLevelOneNotIn(List<String> values) {
            addCriterion("level_one not in", values, "levelOne");
            return (Criteria) this;
        }

        public Criteria andLevelOneBetween(String value1, String value2) {
            addCriterion("level_one between", value1, value2, "levelOne");
            return (Criteria) this;
        }

        public Criteria andLevelOneNotBetween(String value1, String value2) {
            addCriterion("level_one not between", value1, value2, "levelOne");
            return (Criteria) this;
        }

        public Criteria andLevelTwoIsNull() {
            addCriterion("level_two is null");
            return (Criteria) this;
        }

        public Criteria andLevelTwoIsNotNull() {
            addCriterion("level_two is not null");
            return (Criteria) this;
        }

        public Criteria andLevelTwoEqualTo(String value) {
            addCriterion("level_two =", value, "levelTwo");
            return (Criteria) this;
        }

        public Criteria andLevelTwoNotEqualTo(String value) {
            addCriterion("level_two <>", value, "levelTwo");
            return (Criteria) this;
        }

        public Criteria andLevelTwoGreaterThan(String value) {
            addCriterion("level_two >", value, "levelTwo");
            return (Criteria) this;
        }

        public Criteria andLevelTwoGreaterThanOrEqualTo(String value) {
            addCriterion("level_two >=", value, "levelTwo");
            return (Criteria) this;
        }

        public Criteria andLevelTwoLessThan(String value) {
            addCriterion("level_two <", value, "levelTwo");
            return (Criteria) this;
        }

        public Criteria andLevelTwoLessThanOrEqualTo(String value) {
            addCriterion("level_two <=", value, "levelTwo");
            return (Criteria) this;
        }

        public Criteria andLevelTwoLike(String value) {
            addCriterion("level_two like", value, "levelTwo");
            return (Criteria) this;
        }

        public Criteria andLevelTwoNotLike(String value) {
            addCriterion("level_two not like", value, "levelTwo");
            return (Criteria) this;
        }

        public Criteria andLevelTwoIn(List<String> values) {
            addCriterion("level_two in", values, "levelTwo");
            return (Criteria) this;
        }

        public Criteria andLevelTwoNotIn(List<String> values) {
            addCriterion("level_two not in", values, "levelTwo");
            return (Criteria) this;
        }

        public Criteria andLevelTwoBetween(String value1, String value2) {
            addCriterion("level_two between", value1, value2, "levelTwo");
            return (Criteria) this;
        }

        public Criteria andLevelTwoNotBetween(String value1, String value2) {
            addCriterion("level_two not between", value1, value2, "levelTwo");
            return (Criteria) this;
        }

        public Criteria andLevelThreeIsNull() {
            addCriterion("level_three is null");
            return (Criteria) this;
        }

        public Criteria andLevelThreeIsNotNull() {
            addCriterion("level_three is not null");
            return (Criteria) this;
        }

        public Criteria andLevelThreeEqualTo(String value) {
            addCriterion("level_three =", value, "levelThree");
            return (Criteria) this;
        }

        public Criteria andLevelThreeNotEqualTo(String value) {
            addCriterion("level_three <>", value, "levelThree");
            return (Criteria) this;
        }

        public Criteria andLevelThreeGreaterThan(String value) {
            addCriterion("level_three >", value, "levelThree");
            return (Criteria) this;
        }

        public Criteria andLevelThreeGreaterThanOrEqualTo(String value) {
            addCriterion("level_three >=", value, "levelThree");
            return (Criteria) this;
        }

        public Criteria andLevelThreeLessThan(String value) {
            addCriterion("level_three <", value, "levelThree");
            return (Criteria) this;
        }

        public Criteria andLevelThreeLessThanOrEqualTo(String value) {
            addCriterion("level_three <=", value, "levelThree");
            return (Criteria) this;
        }

        public Criteria andLevelThreeLike(String value) {
            addCriterion("level_three like", value, "levelThree");
            return (Criteria) this;
        }

        public Criteria andLevelThreeNotLike(String value) {
            addCriterion("level_three not like", value, "levelThree");
            return (Criteria) this;
        }

        public Criteria andLevelThreeIn(List<String> values) {
            addCriterion("level_three in", values, "levelThree");
            return (Criteria) this;
        }

        public Criteria andLevelThreeNotIn(List<String> values) {
            addCriterion("level_three not in", values, "levelThree");
            return (Criteria) this;
        }

        public Criteria andLevelThreeBetween(String value1, String value2) {
            addCriterion("level_three between", value1, value2, "levelThree");
            return (Criteria) this;
        }

        public Criteria andLevelThreeNotBetween(String value1, String value2) {
            addCriterion("level_three not between", value1, value2, "levelThree");
            return (Criteria) this;
        }

        public Criteria andLevelFourIsNull() {
            addCriterion("level_four is null");
            return (Criteria) this;
        }

        public Criteria andLevelFourIsNotNull() {
            addCriterion("level_four is not null");
            return (Criteria) this;
        }

        public Criteria andLevelFourEqualTo(String value) {
            addCriterion("level_four =", value, "levelFour");
            return (Criteria) this;
        }

        public Criteria andLevelFourNotEqualTo(String value) {
            addCriterion("level_four <>", value, "levelFour");
            return (Criteria) this;
        }

        public Criteria andLevelFourGreaterThan(String value) {
            addCriterion("level_four >", value, "levelFour");
            return (Criteria) this;
        }

        public Criteria andLevelFourGreaterThanOrEqualTo(String value) {
            addCriterion("level_four >=", value, "levelFour");
            return (Criteria) this;
        }

        public Criteria andLevelFourLessThan(String value) {
            addCriterion("level_four <", value, "levelFour");
            return (Criteria) this;
        }

        public Criteria andLevelFourLessThanOrEqualTo(String value) {
            addCriterion("level_four <=", value, "levelFour");
            return (Criteria) this;
        }

        public Criteria andLevelFourLike(String value) {
            addCriterion("level_four like", value, "levelFour");
            return (Criteria) this;
        }

        public Criteria andLevelFourNotLike(String value) {
            addCriterion("level_four not like", value, "levelFour");
            return (Criteria) this;
        }

        public Criteria andLevelFourIn(List<String> values) {
            addCriterion("level_four in", values, "levelFour");
            return (Criteria) this;
        }

        public Criteria andLevelFourNotIn(List<String> values) {
            addCriterion("level_four not in", values, "levelFour");
            return (Criteria) this;
        }

        public Criteria andLevelFourBetween(String value1, String value2) {
            addCriterion("level_four between", value1, value2, "levelFour");
            return (Criteria) this;
        }

        public Criteria andLevelFourNotBetween(String value1, String value2) {
            addCriterion("level_four not between", value1, value2, "levelFour");
            return (Criteria) this;
        }

        public Criteria andLevelFiveIsNull() {
            addCriterion("level_five is null");
            return (Criteria) this;
        }

        public Criteria andLevelFiveIsNotNull() {
            addCriterion("level_five is not null");
            return (Criteria) this;
        }

        public Criteria andLevelFiveEqualTo(String value) {
            addCriterion("level_five =", value, "levelFive");
            return (Criteria) this;
        }

        public Criteria andLevelFiveNotEqualTo(String value) {
            addCriterion("level_five <>", value, "levelFive");
            return (Criteria) this;
        }

        public Criteria andLevelFiveGreaterThan(String value) {
            addCriterion("level_five >", value, "levelFive");
            return (Criteria) this;
        }

        public Criteria andLevelFiveGreaterThanOrEqualTo(String value) {
            addCriterion("level_five >=", value, "levelFive");
            return (Criteria) this;
        }

        public Criteria andLevelFiveLessThan(String value) {
            addCriterion("level_five <", value, "levelFive");
            return (Criteria) this;
        }

        public Criteria andLevelFiveLessThanOrEqualTo(String value) {
            addCriterion("level_five <=", value, "levelFive");
            return (Criteria) this;
        }

        public Criteria andLevelFiveLike(String value) {
            addCriterion("level_five like", value, "levelFive");
            return (Criteria) this;
        }

        public Criteria andLevelFiveNotLike(String value) {
            addCriterion("level_five not like", value, "levelFive");
            return (Criteria) this;
        }

        public Criteria andLevelFiveIn(List<String> values) {
            addCriterion("level_five in", values, "levelFive");
            return (Criteria) this;
        }

        public Criteria andLevelFiveNotIn(List<String> values) {
            addCriterion("level_five not in", values, "levelFive");
            return (Criteria) this;
        }

        public Criteria andLevelFiveBetween(String value1, String value2) {
            addCriterion("level_five between", value1, value2, "levelFive");
            return (Criteria) this;
        }

        public Criteria andLevelFiveNotBetween(String value1, String value2) {
            addCriterion("level_five not between", value1, value2, "levelFive");
            return (Criteria) this;
        }

        public Criteria andLevelSixIsNull() {
            addCriterion("level_six is null");
            return (Criteria) this;
        }

        public Criteria andLevelSixIsNotNull() {
            addCriterion("level_six is not null");
            return (Criteria) this;
        }

        public Criteria andLevelSixEqualTo(String value) {
            addCriterion("level_six =", value, "levelSix");
            return (Criteria) this;
        }

        public Criteria andLevelSixNotEqualTo(String value) {
            addCriterion("level_six <>", value, "levelSix");
            return (Criteria) this;
        }

        public Criteria andLevelSixGreaterThan(String value) {
            addCriterion("level_six >", value, "levelSix");
            return (Criteria) this;
        }

        public Criteria andLevelSixGreaterThanOrEqualTo(String value) {
            addCriterion("level_six >=", value, "levelSix");
            return (Criteria) this;
        }

        public Criteria andLevelSixLessThan(String value) {
            addCriterion("level_six <", value, "levelSix");
            return (Criteria) this;
        }

        public Criteria andLevelSixLessThanOrEqualTo(String value) {
            addCriterion("level_six <=", value, "levelSix");
            return (Criteria) this;
        }

        public Criteria andLevelSixLike(String value) {
            addCriterion("level_six like", value, "levelSix");
            return (Criteria) this;
        }

        public Criteria andLevelSixNotLike(String value) {
            addCriterion("level_six not like", value, "levelSix");
            return (Criteria) this;
        }

        public Criteria andLevelSixIn(List<String> values) {
            addCriterion("level_six in", values, "levelSix");
            return (Criteria) this;
        }

        public Criteria andLevelSixNotIn(List<String> values) {
            addCriterion("level_six not in", values, "levelSix");
            return (Criteria) this;
        }

        public Criteria andLevelSixBetween(String value1, String value2) {
            addCriterion("level_six between", value1, value2, "levelSix");
            return (Criteria) this;
        }

        public Criteria andLevelSixNotBetween(String value1, String value2) {
            addCriterion("level_six not between", value1, value2, "levelSix");
            return (Criteria) this;
        }

        public Criteria andLevelSevenIsNull() {
            addCriterion("level_seven is null");
            return (Criteria) this;
        }

        public Criteria andLevelSevenIsNotNull() {
            addCriterion("level_seven is not null");
            return (Criteria) this;
        }

        public Criteria andLevelSevenEqualTo(String value) {
            addCriterion("level_seven =", value, "levelSeven");
            return (Criteria) this;
        }

        public Criteria andLevelSevenNotEqualTo(String value) {
            addCriterion("level_seven <>", value, "levelSeven");
            return (Criteria) this;
        }

        public Criteria andLevelSevenGreaterThan(String value) {
            addCriterion("level_seven >", value, "levelSeven");
            return (Criteria) this;
        }

        public Criteria andLevelSevenGreaterThanOrEqualTo(String value) {
            addCriterion("level_seven >=", value, "levelSeven");
            return (Criteria) this;
        }

        public Criteria andLevelSevenLessThan(String value) {
            addCriterion("level_seven <", value, "levelSeven");
            return (Criteria) this;
        }

        public Criteria andLevelSevenLessThanOrEqualTo(String value) {
            addCriterion("level_seven <=", value, "levelSeven");
            return (Criteria) this;
        }

        public Criteria andLevelSevenLike(String value) {
            addCriterion("level_seven like", value, "levelSeven");
            return (Criteria) this;
        }

        public Criteria andLevelSevenNotLike(String value) {
            addCriterion("level_seven not like", value, "levelSeven");
            return (Criteria) this;
        }

        public Criteria andLevelSevenIn(List<String> values) {
            addCriterion("level_seven in", values, "levelSeven");
            return (Criteria) this;
        }

        public Criteria andLevelSevenNotIn(List<String> values) {
            addCriterion("level_seven not in", values, "levelSeven");
            return (Criteria) this;
        }

        public Criteria andLevelSevenBetween(String value1, String value2) {
            addCriterion("level_seven between", value1, value2, "levelSeven");
            return (Criteria) this;
        }

        public Criteria andLevelSevenNotBetween(String value1, String value2) {
            addCriterion("level_seven not between", value1, value2, "levelSeven");
            return (Criteria) this;
        }

        public Criteria andLevelEightIsNull() {
            addCriterion("level_eight is null");
            return (Criteria) this;
        }

        public Criteria andLevelEightIsNotNull() {
            addCriterion("level_eight is not null");
            return (Criteria) this;
        }

        public Criteria andLevelEightEqualTo(String value) {
            addCriterion("level_eight =", value, "levelEight");
            return (Criteria) this;
        }

        public Criteria andLevelEightNotEqualTo(String value) {
            addCriterion("level_eight <>", value, "levelEight");
            return (Criteria) this;
        }

        public Criteria andLevelEightGreaterThan(String value) {
            addCriterion("level_eight >", value, "levelEight");
            return (Criteria) this;
        }

        public Criteria andLevelEightGreaterThanOrEqualTo(String value) {
            addCriterion("level_eight >=", value, "levelEight");
            return (Criteria) this;
        }

        public Criteria andLevelEightLessThan(String value) {
            addCriterion("level_eight <", value, "levelEight");
            return (Criteria) this;
        }

        public Criteria andLevelEightLessThanOrEqualTo(String value) {
            addCriterion("level_eight <=", value, "levelEight");
            return (Criteria) this;
        }

        public Criteria andLevelEightLike(String value) {
            addCriterion("level_eight like", value, "levelEight");
            return (Criteria) this;
        }

        public Criteria andLevelEightNotLike(String value) {
            addCriterion("level_eight not like", value, "levelEight");
            return (Criteria) this;
        }

        public Criteria andLevelEightIn(List<String> values) {
            addCriterion("level_eight in", values, "levelEight");
            return (Criteria) this;
        }

        public Criteria andLevelEightNotIn(List<String> values) {
            addCriterion("level_eight not in", values, "levelEight");
            return (Criteria) this;
        }

        public Criteria andLevelEightBetween(String value1, String value2) {
            addCriterion("level_eight between", value1, value2, "levelEight");
            return (Criteria) this;
        }

        public Criteria andLevelEightNotBetween(String value1, String value2) {
            addCriterion("level_eight not between", value1, value2, "levelEight");
            return (Criteria) this;
        }

        public Criteria andSuperGradeIsNull() {
            addCriterion("super_grade is null");
            return (Criteria) this;
        }

        public Criteria andSuperGradeIsNotNull() {
            addCriterion("super_grade is not null");
            return (Criteria) this;
        }

        public Criteria andSuperGradeEqualTo(String value) {
            addCriterion("super_grade =", value, "superGrade");
            return (Criteria) this;
        }

        public Criteria andSuperGradeNotEqualTo(String value) {
            addCriterion("super_grade <>", value, "superGrade");
            return (Criteria) this;
        }

        public Criteria andSuperGradeGreaterThan(String value) {
            addCriterion("super_grade >", value, "superGrade");
            return (Criteria) this;
        }

        public Criteria andSuperGradeGreaterThanOrEqualTo(String value) {
            addCriterion("super_grade >=", value, "superGrade");
            return (Criteria) this;
        }

        public Criteria andSuperGradeLessThan(String value) {
            addCriterion("super_grade <", value, "superGrade");
            return (Criteria) this;
        }

        public Criteria andSuperGradeLessThanOrEqualTo(String value) {
            addCriterion("super_grade <=", value, "superGrade");
            return (Criteria) this;
        }

        public Criteria andSuperGradeLike(String value) {
            addCriterion("super_grade like", value, "superGrade");
            return (Criteria) this;
        }

        public Criteria andSuperGradeNotLike(String value) {
            addCriterion("super_grade not like", value, "superGrade");
            return (Criteria) this;
        }

        public Criteria andSuperGradeIn(List<String> values) {
            addCriterion("super_grade in", values, "superGrade");
            return (Criteria) this;
        }

        public Criteria andSuperGradeNotIn(List<String> values) {
            addCriterion("super_grade not in", values, "superGrade");
            return (Criteria) this;
        }

        public Criteria andSuperGradeBetween(String value1, String value2) {
            addCriterion("super_grade between", value1, value2, "superGrade");
            return (Criteria) this;
        }

        public Criteria andSuperGradeNotBetween(String value1, String value2) {
            addCriterion("super_grade not between", value1, value2, "superGrade");
            return (Criteria) this;
        }

        public Criteria andSuperClassIsNull() {
            addCriterion("super_class is null");
            return (Criteria) this;
        }

        public Criteria andSuperClassIsNotNull() {
            addCriterion("super_class is not null");
            return (Criteria) this;
        }

        public Criteria andSuperClassEqualTo(String value) {
            addCriterion("super_class =", value, "superClass");
            return (Criteria) this;
        }

        public Criteria andSuperClassNotEqualTo(String value) {
            addCriterion("super_class <>", value, "superClass");
            return (Criteria) this;
        }

        public Criteria andSuperClassGreaterThan(String value) {
            addCriterion("super_class >", value, "superClass");
            return (Criteria) this;
        }

        public Criteria andSuperClassGreaterThanOrEqualTo(String value) {
            addCriterion("super_class >=", value, "superClass");
            return (Criteria) this;
        }

        public Criteria andSuperClassLessThan(String value) {
            addCriterion("super_class <", value, "superClass");
            return (Criteria) this;
        }

        public Criteria andSuperClassLessThanOrEqualTo(String value) {
            addCriterion("super_class <=", value, "superClass");
            return (Criteria) this;
        }

        public Criteria andSuperClassLike(String value) {
            addCriterion("super_class like", value, "superClass");
            return (Criteria) this;
        }

        public Criteria andSuperClassNotLike(String value) {
            addCriterion("super_class not like", value, "superClass");
            return (Criteria) this;
        }

        public Criteria andSuperClassIn(List<String> values) {
            addCriterion("super_class in", values, "superClass");
            return (Criteria) this;
        }

        public Criteria andSuperClassNotIn(List<String> values) {
            addCriterion("super_class not in", values, "superClass");
            return (Criteria) this;
        }

        public Criteria andSuperClassBetween(String value1, String value2) {
            addCriterion("super_class between", value1, value2, "superClass");
            return (Criteria) this;
        }

        public Criteria andSuperClassNotBetween(String value1, String value2) {
            addCriterion("super_class not between", value1, value2, "superClass");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table course_schedule
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table course_schedule
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}