package com.smlearning.domain.entity;

import java.util.Date;

import com.smlearning.infrastructure.utils.DateUtil;

public class Courseware {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courseware.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courseware.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courseware.courseware_category_id
     *
     * @mbggenerated
     */
    private Long coursewareCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courseware.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courseware.created_time
     *
     * @mbggenerated
     */
    private Date createdTime;
    
    private String strCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courseware.creator
     *
     * @mbggenerated
     */
    private Long creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courseware.pic
     *
     * @mbggenerated
     */
    private String pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courseware.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courseware.class_id
     *
     * @mbggenerated
     */
    private Long classId;
    
    
    private Long gradeId = 0L;
    
    private Integer isPublic = 0;

    
    
    public Integer getIsPublic() {
		return isPublic;
	}

	public void setIsPublic(Integer isPublic) {
		this.isPublic = isPublic;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseware.id
     *
     * @return the value of courseware.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseware.id
     *
     * @param id the value for courseware.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseware.name
     *
     * @return the value of courseware.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseware.name
     *
     * @param name the value for courseware.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseware.courseware_category_id
     *
     * @return the value of courseware.courseware_category_id
     *
     * @mbggenerated
     */
    public Long getCoursewareCategoryId() {
        return coursewareCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseware.courseware_category_id
     *
     * @param coursewareCategoryId the value for courseware.courseware_category_id
     *
     * @mbggenerated
     */
    public void setCoursewareCategoryId(Long coursewareCategoryId) {
        this.coursewareCategoryId = coursewareCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseware.url
     *
     * @return the value of courseware.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseware.url
     *
     * @param url the value for courseware.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseware.created_time
     *
     * @return the value of courseware.created_time
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseware.created_time
     *
     * @param createdTime the value for courseware.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
        this.setStrCreateTime(DateUtil.dateToString(createdTime,false));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseware.creator
     *
     * @return the value of courseware.creator
     *
     * @mbggenerated
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseware.creator
     *
     * @param creator the value for courseware.creator
     *
     * @mbggenerated
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseware.pic
     *
     * @return the value of courseware.pic
     *
     * @mbggenerated
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseware.pic
     *
     * @param pic the value for courseware.pic
     *
     * @mbggenerated
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseware.status
     *
     * @return the value of courseware.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseware.status
     *
     * @param status the value for courseware.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courseware.class_id
     *
     * @return the value of courseware.class_id
     *
     * @mbggenerated
     */
    public Long getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courseware.class_id
     *
     * @param classId the value for courseware.class_id
     *
     * @mbggenerated
     */
    public void setClassId(Long classId) {
        this.classId = classId;
    }

	public Long getGradeId() {
		return gradeId;
	}

	public void setGradeId(Long gradeId) {
		this.gradeId = gradeId;
	}

	public String getStrCreateTime() {
		return strCreateTime;
	}

	public void setStrCreateTime(String strCreateTime) {
		this.strCreateTime = strCreateTime;
	}
    
    
}