package com.smlearning.domain.entity;

public class Lesson {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson.class_id
     *
     * @mbggenerated
     */
    private Long classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson.subject_id
     *
     * @mbggenerated
     */
    private Long subjectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson.day
     *
     * @mbggenerated
     */
    private Integer day;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson.thetime
     *
     * @mbggenerated
     */
    private Integer thetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson.year
     *
     * @mbggenerated
     */
    private Integer year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson.term
     *
     * @mbggenerated
     */
    private Integer term;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson.id
     *
     * @return the value of lesson.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson.id
     *
     * @param id the value for lesson.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson.class_id
     *
     * @return the value of lesson.class_id
     *
     * @mbggenerated
     */
    public Long getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson.class_id
     *
     * @param classId the value for lesson.class_id
     *
     * @mbggenerated
     */
    public void setClassId(Long classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson.subject_id
     *
     * @return the value of lesson.subject_id
     *
     * @mbggenerated
     */
    public Long getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson.subject_id
     *
     * @param subjectId the value for lesson.subject_id
     *
     * @mbggenerated
     */
    public void setSubjectId(Long subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson.day
     *
     * @return the value of lesson.day
     *
     * @mbggenerated
     */
    public Integer getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson.day
     *
     * @param day the value for lesson.day
     *
     * @mbggenerated
     */
    public void setDay(Integer day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson.thetime
     *
     * @return the value of lesson.thetime
     *
     * @mbggenerated
     */
    public Integer getThetime() {
        return thetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson.thetime
     *
     * @param thetime the value for lesson.thetime
     *
     * @mbggenerated
     */
    public void setThetime(Integer thetime) {
        this.thetime = thetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson.year
     *
     * @return the value of lesson.year
     *
     * @mbggenerated
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson.year
     *
     * @param year the value for lesson.year
     *
     * @mbggenerated
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson.term
     *
     * @return the value of lesson.term
     *
     * @mbggenerated
     */
    public Integer getTerm() {
        return term;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson.term
     *
     * @param term the value for lesson.term
     *
     * @mbggenerated
     */
    public void setTerm(Integer term) {
        this.term = term;
    }
}