package com.smlearning.domain.entity;

import java.util.Date;

public class userCourseNote {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_course_note.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_course_note.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_course_note.courseware_id
     *
     * @mbggenerated
     */
    private Long coursewareId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_course_note.created_time
     *
     * @mbggenerated
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_course_note.note
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_course_note.id
     *
     * @return the value of user_course_note.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_course_note.id
     *
     * @param id the value for user_course_note.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_course_note.user_id
     *
     * @return the value of user_course_note.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_course_note.user_id
     *
     * @param userId the value for user_course_note.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_course_note.courseware_id
     *
     * @return the value of user_course_note.courseware_id
     *
     * @mbggenerated
     */
    public Long getCoursewareId() {
        return coursewareId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_course_note.courseware_id
     *
     * @param coursewareId the value for user_course_note.courseware_id
     *
     * @mbggenerated
     */
    public void setCoursewareId(Long coursewareId) {
        this.coursewareId = coursewareId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_course_note.created_time
     *
     * @return the value of user_course_note.created_time
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_course_note.created_time
     *
     * @param createdTime the value for user_course_note.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_course_note.note
     *
     * @return the value of user_course_note.note
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_course_note.note
     *
     * @param note the value for user_course_note.note
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}