package com.smlearning.domain.entity;

public class userTestPaper {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_test_paper.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_test_paper.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_test_paper.question_id
     *
     * @mbggenerated
     */
    private Long questionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_test_paper.time
     *
     * @mbggenerated
     */
    private String time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_test_paper.score
     *
     * @mbggenerated
     */
    private String score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_test_paper.is_correct
     *
     * @mbggenerated
     */
    private String isCorrect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_test_paper.test_paper_id
     *
     * @mbggenerated
     */
    private Long testPaperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_test_paper.no_select_answer
     *
     * @mbggenerated
     */
    private byte[] noSelectAnswer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_test_paper.id
     *
     * @return the value of user_test_paper.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_test_paper.id
     *
     * @param id the value for user_test_paper.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_test_paper.user_id
     *
     * @return the value of user_test_paper.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_test_paper.user_id
     *
     * @param userId the value for user_test_paper.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_test_paper.question_id
     *
     * @return the value of user_test_paper.question_id
     *
     * @mbggenerated
     */
    public Long getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_test_paper.question_id
     *
     * @param questionId the value for user_test_paper.question_id
     *
     * @mbggenerated
     */
    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_test_paper.time
     *
     * @return the value of user_test_paper.time
     *
     * @mbggenerated
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_test_paper.time
     *
     * @param time the value for user_test_paper.time
     *
     * @mbggenerated
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_test_paper.score
     *
     * @return the value of user_test_paper.score
     *
     * @mbggenerated
     */
    public String getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_test_paper.score
     *
     * @param score the value for user_test_paper.score
     *
     * @mbggenerated
     */
    public void setScore(String score) {
        this.score = score == null ? null : score.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_test_paper.is_correct
     *
     * @return the value of user_test_paper.is_correct
     *
     * @mbggenerated
     */
    public String getIsCorrect() {
        return isCorrect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_test_paper.is_correct
     *
     * @param isCorrect the value for user_test_paper.is_correct
     *
     * @mbggenerated
     */
    public void setIsCorrect(String isCorrect) {
        this.isCorrect = isCorrect == null ? null : isCorrect.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_test_paper.test_paper_id
     *
     * @return the value of user_test_paper.test_paper_id
     *
     * @mbggenerated
     */
    public Long getTestPaperId() {
        return testPaperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_test_paper.test_paper_id
     *
     * @param testPaperId the value for user_test_paper.test_paper_id
     *
     * @mbggenerated
     */
    public void setTestPaperId(Long testPaperId) {
        this.testPaperId = testPaperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_test_paper.no_select_answer
     *
     * @return the value of user_test_paper.no_select_answer
     *
     * @mbggenerated
     */
    public byte[] getNoSelectAnswer() {
        return noSelectAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_test_paper.no_select_answer
     *
     * @param noSelectAnswer the value for user_test_paper.no_select_answer
     *
     * @mbggenerated
     */
    public void setNoSelectAnswer(byte[] noSelectAnswer) {
        this.noSelectAnswer = noSelectAnswer;
    }
}