package com.smlearning.domain.vo;


public class CoursePlanVO implements java.io.Serializable {

	private static final long serialVersionUID = 8183728726629082353L;
	
	    public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getImageUrl() {
		return imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

		private Long id;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column course_plan.name
	     *
	     * @mbggenerated
	     */
	    private String name;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column course_plan.image_url
	     *
	     * @mbggenerated
	     */
	    private String imageUrl;
	    
	    private long gradeId = 0;

      public long getGradeId() {
        return gradeId;
      }

      public void setGradeId(long gradeId) {
        this.gradeId = gradeId;
      }
	    
	    
}
