package com.smlearning.infrastructure.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.smlearning.domain.entity.CoursePlan;
import com.smlearning.domain.entity.CoursePlanExample;

public interface CoursePlanMapper {
	
	/**
	 * 分页查询
	 * @param example
	 * @return
	 */
	List<CoursePlan> selectByExamplePaging(CoursePlanExample example);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_plan
     *
     * @mbggenerated
     */
    int countByExample(CoursePlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_plan
     *
     * @mbggenerated
     */
    int deleteByExample(CoursePlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_plan
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_plan
     *
     * @mbggenerated
     */
    int insert(CoursePlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_plan
     *
     * @mbggenerated
     */
    int insertSelective(CoursePlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_plan
     *
     * @mbggenerated
     */
    List<CoursePlan> selectByExample(CoursePlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_plan
     *
     * @mbggenerated
     */
    CoursePlan selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_plan
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CoursePlan record, @Param("example") CoursePlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_plan
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CoursePlan record, @Param("example") CoursePlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_plan
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CoursePlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_plan
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CoursePlan record);
}