package com.smlearning.infrastructure.dao;

import com.smlearning.domain.entity.Courseware;
import com.smlearning.domain.entity.CoursewareExample;
import com.smlearning.domain.entity.extend.CoursewareExtend;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface CoursewareMapper {
	
	/**
	 * 分页查询
	 * @param example
	 * @return
	 */
	List<CoursewareExtend> selectByExamplePagings(CoursewareExample example);
	
	int countByExamplePagings(CoursewareExample example);
	/**
	 * 分页查询
	 * @param example
	 * @return
	 */
	List<CoursewareExtend> selectByExamplePaging(CoursewareExample example);
	
	int countByExamplePaging(CoursewareExample example);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseware
     *
     * @mbggenerated
     */
    int countByExample(CoursewareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseware
     *
     * @mbggenerated
     */
    int deleteByExample(CoursewareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseware
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseware
     *
     * @mbggenerated
     */
    int insert(Courseware record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseware
     *
     * @mbggenerated
     */
    int insertSelective(Courseware record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseware
     *
     * @mbggenerated
     */
    List<Courseware> selectByExample(CoursewareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseware
     *
     * @mbggenerated
     */
    Courseware selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseware
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Courseware record, @Param("example") CoursewareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseware
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Courseware record, @Param("example") CoursewareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseware
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Courseware record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseware
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Courseware record);
}