package com.smlearning.infrastructure.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.smlearning.domain.entity.courseTable;
import com.smlearning.domain.entity.courseTableExample;

public interface courseTableMapper {
	
	/**
	 * 分页查询
	 * @param example
	 * @return
	 */
	List<courseTable> selectByExamplePaging(courseTableExample example);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbggenerated
     */
    int countByExample(courseTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbggenerated
     */
    int deleteByExample(courseTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbggenerated
     */
    int insert(courseTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbggenerated
     */
    int insertSelective(courseTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbggenerated
     */
    List<courseTable> selectByExample(courseTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbggenerated
     */
    courseTable selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") courseTable record, @Param("example") courseTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") courseTable record, @Param("example") courseTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(courseTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_table
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(courseTable record);
}