package com.smlearning.infrastructure.dao;

import com.smlearning.domain.entity.CoursewareCategory;
import com.smlearning.domain.entity.CoursewareCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CoursewareCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseware_category
     *
     * @mbggenerated
     */
    int countByExample(CoursewareCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseware_category
     *
     * @mbggenerated
     */
    int deleteByExample(CoursewareCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseware_category
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseware_category
     *
     * @mbggenerated
     */
    int insert(CoursewareCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseware_category
     *
     * @mbggenerated
     */
    int insertSelective(CoursewareCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseware_category
     *
     * @mbggenerated
     */
    List<CoursewareCategory> selectByExample(CoursewareCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseware_category
     *
     * @mbggenerated
     */
    CoursewareCategory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseware_category
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CoursewareCategory record, @Param("example") CoursewareCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseware_category
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CoursewareCategory record, @Param("example") CoursewareCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseware_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CoursewareCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courseware_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CoursewareCategory record);
}