package com.smlearning.infrastructure.dao;

import com.smlearning.domain.entity.CourseCourseware;
import com.smlearning.domain.entity.CourseCoursewareExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CourseCoursewareMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_courseware
     *
     * @mbggenerated
     */
    int countByExample(CourseCoursewareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_courseware
     *
     * @mbggenerated
     */
    int deleteByExample(CourseCoursewareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_courseware
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_courseware
     *
     * @mbggenerated
     */
    int insert(CourseCourseware record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_courseware
     *
     * @mbggenerated
     */
    int insertSelective(CourseCourseware record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_courseware
     *
     * @mbggenerated
     */
    List<CourseCourseware> selectByExample(CourseCoursewareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_courseware
     *
     * @mbggenerated
     */
    CourseCourseware selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_courseware
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CourseCourseware record, @Param("example") CourseCoursewareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_courseware
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CourseCourseware record, @Param("example") CourseCoursewareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_courseware
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CourseCourseware record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_courseware
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CourseCourseware record);
}