package com.smlearning.infrastructure.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.smlearning.domain.entity.CourseSchedule;
import com.smlearning.domain.entity.CourseScheduleExample;

public interface CourseScheduleMapper {
	
	/**
	 * 分页查询
	 * @param example
	 * @return
	 */
	List<CourseSchedule> selectByExamplePaging(CourseScheduleExample example);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_schedule
     *
     * @mbggenerated
     */
    int countByExample(CourseScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_schedule
     *
     * @mbggenerated
     */
    int deleteByExample(CourseScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_schedule
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_schedule
     *
     * @mbggenerated
     */
    int insert(CourseSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_schedule
     *
     * @mbggenerated
     */
    int insertSelective(CourseSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_schedule
     *
     * @mbggenerated
     */
    List<CourseSchedule> selectByExample(CourseScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_schedule
     *
     * @mbggenerated
     */
    CourseSchedule selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_schedule
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CourseSchedule record, @Param("example") CourseScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_schedule
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CourseSchedule record, @Param("example") CourseScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_schedule
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CourseSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_schedule
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CourseSchedule record);
}