package com.smlearning.infrastructure.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.smlearning.domain.entity.Lesson;
import com.smlearning.domain.entity.LessonExample;
import com.smlearning.domain.entity.extend.LessonExtend;

public interface LessonMapper {
	
	/**
	 * 分页查询
	 * @param example
	 * @return
	 */
	List<LessonExtend> selectByExamplePaging(LessonExample example);
	
	/**
	 * 
	 * @param example
	 * @return
	 */
	List<LessonExtend> selectByExampleAll(LessonExample example);
	
	
    int selectByExamplePagingCount(LessonExample example);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson
     *
     * @mbggenerated
     */
    int countByExample(LessonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson
     *
     * @mbggenerated
     */
    int deleteByExample(LessonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson
     *
     * @mbggenerated
     */
    int insert(Lesson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson
     *
     * @mbggenerated
     */
    int insertSelective(Lesson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson
     *
     * @mbggenerated
     */
    List<Lesson> selectByExample(LessonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson
     *
     * @mbggenerated
     */
    Lesson selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Lesson record, @Param("example") LessonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Lesson record, @Param("example") LessonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Lesson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Lesson record);
}