package com.smlearning.infrastructure.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.smlearning.domain.entity.Organ;
import com.smlearning.domain.entity.OrganExample;
@Repository
public interface OrganMapper {
	
	/**
	 * 分页查询
	 * @param example
	 * @return
	 */
	List<Organ> selectByExamplePaging(OrganExample example);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organ
     *
     * @mbggenerated
     */
    int countByExample(OrganExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organ
     *
     * @mbggenerated
     */
    int deleteByExample(OrganExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organ
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organ
     *
     * @mbggenerated
     */
    int insert(Organ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organ
     *
     * @mbggenerated
     */
    int insertSelective(Organ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organ
     *
     * @mbggenerated
     */
    List<Organ> selectByExample(OrganExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organ
     *
     * @mbggenerated
     */
    Organ selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organ
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Organ record, @Param("example") OrganExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organ
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Organ record, @Param("example") OrganExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organ
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Organ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organ
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Organ record);
}