package com.smlearning.infrastructure.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.smlearning.domain.entity.SysKey;
import com.smlearning.domain.entity.SysKeyExample;
@Repository
public interface SysKeyMapper {
	
	/**
	 * 分页查询
	 * @param example
	 * @return
	 */
	List<SysKey> selectByExamplePaging(SysKeyExample example);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_key
     *
     * @mbggenerated
     */
    int countByExample(SysKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_key
     *
     * @mbggenerated
     */
    int deleteByExample(SysKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_key
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_key
     *
     * @mbggenerated
     */
    int insert(SysKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_key
     *
     * @mbggenerated
     */
    int insertSelective(SysKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_key
     *
     * @mbggenerated
     */
    List<SysKey> selectByExample(SysKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_key
     *
     * @mbggenerated
     */
    SysKey selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_key
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysKey record, @Param("example") SysKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_key
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysKey record, @Param("example") SysKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_key
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_key
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysKey record);
}