package com.smlearning.infrastructure.dao;

import com.smlearning.domain.entity.SysMessage;
import com.smlearning.domain.entity.SysMessageExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
@Repository
public interface SysMessageMapper {
	
	/**
	 * 分页查询
	 * @param example
	 * @return
	 */
	List<SysMessage> selectByExamplePaging(SysMessageExample example);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_message
     *
     * @mbggenerated
     */
    int countByExample(SysMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_message
     *
     * @mbggenerated
     */
    int deleteByExample(SysMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_message
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_message
     *
     * @mbggenerated
     */
    int insert(SysMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_message
     *
     * @mbggenerated
     */
    int insertSelective(SysMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_message
     *
     * @mbggenerated
     */
    List<SysMessage> selectByExampleWithBLOBs(SysMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_message
     *
     * @mbggenerated
     */
    List<SysMessage> selectByExample(SysMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_message
     *
     * @mbggenerated
     */
    SysMessage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_message
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysMessage record, @Param("example") SysMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_message
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") SysMessage record, @Param("example") SysMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_message
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysMessage record, @Param("example") SysMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(SysMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysMessage record);
}