package com.smlearning.infrastructure.dao;

import com.smlearning.domain.entity.userTestPaper;
import com.smlearning.domain.entity.userTestPaperExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface userTestPaperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test_paper
     *
     * @mbggenerated
     */
    int countByExample(userTestPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test_paper
     *
     * @mbggenerated
     */
    int deleteByExample(userTestPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test_paper
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test_paper
     *
     * @mbggenerated
     */
    int insert(userTestPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test_paper
     *
     * @mbggenerated
     */
    int insertSelective(userTestPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test_paper
     *
     * @mbggenerated
     */
    List<userTestPaper> selectByExampleWithBLOBs(userTestPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test_paper
     *
     * @mbggenerated
     */
    List<userTestPaper> selectByExample(userTestPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test_paper
     *
     * @mbggenerated
     */
    userTestPaper selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test_paper
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") userTestPaper record, @Param("example") userTestPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test_paper
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") userTestPaper record, @Param("example") userTestPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test_paper
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") userTestPaper record, @Param("example") userTestPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test_paper
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(userTestPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test_paper
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(userTestPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test_paper
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(userTestPaper record);
}